TrainingArguments:
  num_train_epochs: 3
  warmup_steps: 100
  per_device_train_batch_size: 2
  weight_decay: 0.01
  logging_steps: 50
  evaluation_strategy: epoch
  early_stop_paitence : 3
  val_split_size : 0.1
  val_split_seed : 42
  save_steps: 500
  gradient_accumulation_steps: 4
  
